import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "rest-api/management/ant-media-server-management-panel-rest-api",
    },
    {
      type: "category",
      label: "UNTAGGED",
      items: [
        {
          type: "doc",
          id: "rest-api/management/delete-node",
          label: "deleteNode",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/management/get-node-count",
          label: "getNodeCount",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-node-list",
          label: "getNodeList",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/delete-node-1",
          label: "deleteNode_1",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-node-count-1",
          label: "getNodeCount_1",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-node-list-1",
          label: "getNodeList_1",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/add-initial-user",
          label: "Creates initial user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/management/edit-user",
          label: "Edit the user",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/management/add-user",
          label: "Creates a new user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/management/authenticate-user",
          label: "Authenticates user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/management/get-server-settings",
          label: "Returns the server settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/change-server-settings",
          label: "Changes server settings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/management/get-settings",
          label: "Returns the specified application settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/change-settings",
          label: "Changes the application settings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/management/change-user-password",
          label: "Changes the given user's password",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/management/configure-ssl",
          label: "Changes ssl settings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/management/create-application-1",
          label: "Creates a new application with given name and supports uploading custom WAR files",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/management/create-application",
          label: "Creates a new application with given name",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/management/delete-application",
          label: "Deletes application with the given name",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/management/delete-session",
          label: "deleteSession",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/management/delete-user",
          label: "Delete the user",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/management/get-app-live-streams",
          label: "Returns live streams in the specified application",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-application-info",
          label: "Gets application info",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-applications",
          label: "Gets the applications in the server",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-blocked-status",
          label: "Returns if user is blocked",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-cpu-info",
          label: "Returns system cpu load, process cpu load and process cpu time",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-file-system-info",
          label: "Gets system file status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-gpu-info",
          label: "Gets GPU information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-heap-dump",
          label: "Returns heap dump",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-jvm-memory-info",
          label: "Returns JVM memory information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-licence-status",
          label: "Returns the last checked license status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-licence-status-1",
          label: "Returns license status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-log-file",
          label: "Gets log file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-server-time",
          label: "Gets server time",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-system-info",
          label: "Returns system information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-system-memory-info",
          label: "Gets system memory status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-system-resources-info",
          label: "Gets system resource information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-thread-dump",
          label: "Gets thread dump in plain text",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-thread-dump-json",
          label: "Gets thread dump in json format",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-threads-info",
          label: "Returns processor's thread information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-total-live-stream-size",
          label: "Returns total number of live streams",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-user-list",
          label: "Returns user list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/get-version",
          label: "Returns the version of Ant Media Server",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/is-admin",
          label: "Returns admin status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/is-authenticated-rest",
          label: "Returns true if user is authenticated to call rest api operations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/is-enterprise-edition",
          label: "Returns true if the server is enterprise edition",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/is-first-login",
          label: "Checks first login status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/is-in-cluster-mode",
          label: "Returns the server mode",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/is-shutdown-properly",
          label: "Checks whether application or applications have shutdown properly",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/liveness",
          label: "Returns the hostname to check liveness with HTTP type healthcheck",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/reset-broadcast",
          label: "Resets the viewer counts and broadcasts statuses in the db",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/management/set-shutdown-status",
          label: "Set application or applications shutdown property to true",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/management/trigger-gc",
          label: "Trigger garbage collector",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/management/send-support-request",
          label: "sendSupportRequest",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
