import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "rest-api/application/ant-media-server-rest-api-reference",
    },
    {
      type: "category",
      label: "UNTAGGED",
      items: [
        {
          type: "doc",
          id: "rest-api/application/add-endpoint",
          label: "Adds a third party RTMP or SRT end point to the stream",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/application/remove-endpoint",
          label: "Removes a third party RTMP or SRT end point from the stream",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/application/add-id-3-data",
          label: "addID3Data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/application/add-sei-data",
          label: "addSEIData",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/application/add-sub-track",
          label: "Add a subtrack to a main track (broadcast)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/application/remove-sub-track",
          label: "Delete a subtrack from a main track (broadcast)",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/application/add-subscriber",
          label: "Add Subscriber to the requested stream",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/application/revoke-subscribers",
          label: "Removes all subscribers related to the requested stream",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/application/block-subscriber",
          label: "Block specific subscriber",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/application/convert-hl-sto-mp-4",
          label: "convertHLStoMP4",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/application/create-broadcast",
          label: "createBroadcast",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/application/get-broadcast",
          label: "getBroadcast",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/update-broadcast",
          label: "updateBroadcast",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/application/delete-broadcast",
          label: "Delete broadcast from data store and stop if it's broadcasting",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/application/delete-broadcasts-bulk",
          label: "deleteBroadcastsBulk",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/application/delete-subscriber",
          label: "Delete specific subscriber from data store",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/application/enable-recording",
          label: "Set stream specific recording setting",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/application/get-active-subtracks",
          label: "Get active subtracks of a broadcast",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-active-subtracks-count",
          label: "Get count of active subtracks of a broadcast",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-app-live-statistics",
          label: "Return the active live streams",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-broadcast-list",
          label: "getBroadcastList",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-broadcast-statistics",
          label: "Get the broadcast live statistics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-broadcast-total-statistics",
          label: "Get total broadcast live statistics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-camera-error-v-2",
          label: "Get IP Camera Error after connection failure",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-connection-events",
          label: "Retrieve all subscriber statistics of the requested stream. ",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-duration",
          label: "getDuration",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-jwt-token-v-2",
          label: "getJwtTokenV2",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-onvif-device-profiles",
          label: "Get the Profile List for an ONVIF IP Camera",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-stream-info",
          label: "Get stream information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-subtracks",
          label: "Get subtracks of a broadcast",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-totp",
          label: "getTOTP",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-token-v-2",
          label: "getTokenV2",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-total-broadcast-number-v-2",
          label: "Get the total number of broadcasts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-total-broadcast-number-v-2-1",
          label: "Get the number of broadcasts based on search criteria",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-web-rtc-client-stats-list-v-2",
          label: "Get WebRTC Client Statistics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-web-rtc-low-level-receive-stats",
          label: "Get WebRTC Low Level Receive Stats",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-web-rtc-low-level-send-stats",
          label: "Get WebRTC Low Level Send Stats",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/list-subscriber-v-2",
          label: "Get all subscribers of the requested stream",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/list-tokens-v-2",
          label: "Get all tokens of requested stream",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/move-ip-camera",
          label: "Move IP Camera",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/application/play-next-item",
          label: "Specify the next playlist item to play by index",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/application/revoke-tokens-v-2",
          label: "Removes all tokens related with requested stream",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/application/search-onvif-devices-v-2",
          label: "Get Discovered ONVIF IP Cameras",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/send-message",
          label: "Send message to stream participants via Data Channel",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/application/start-stream-source-v-2",
          label: "Start streaming sources",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/application/stop-move",
          label: "stopMove",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/application/stop-streaming-v-2",
          label: "Stop streaming for the active stream",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/application/update-seek-time",
          label: "updateSeekTime",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/application/validate-token-v-2",
          label: "Perform validation of token for requested stream",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/application/create",
          label: "Creates or update the filter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/application/create-mcu",
          label: "Creates MCU for the roomo in the parameter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/application/delete-mcu",
          label: "Deletes MCU filter for non MCU room",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/application/delete",
          label: "Delete the filter according to the filterId",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/application/get-filters",
          label: "Returns the list of filters effective in the application",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/reset-mcu-filter",
          label: "Reset the default MCU filter",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/application/set-custom-mcu-filter",
          label: "Set a filter specific to the MCU room",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/application/set-plugin-type",
          label: "Set the plugin type of the MCU function",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest-api/application/get-subscriber-authentication-token",
          label: "getSubscriberAuthenticationToken",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/send-push-notification",
          label: "sendPushNotification",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/application/send-push-notification-1",
          label: "sendPushNotification_1",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/application/get-version",
          label: "Returns the Ant Media Server Version",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-vo-d",
          label: "VoD file from database",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/delete-vo-d",
          label: "Delete specific VoD File",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/application/delete-vo-ds-bulk",
          label: "Delete bulk VoD Files based on Vod Id",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/application/get-total-vod-number",
          label: "Get the total number of VoDs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-total-vod-number-1",
          label: "Get the partial number of VoDs depending on the searched items",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/get-vod-list",
          label: "Get the VoD list from database",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest-api/application/import-vo-ds",
          label: "Import VoD files from a directory and make them streamable.",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest-api/application/unlinks-vo-d",
          label: "Unlinks VoD path from streams directory and delete the database record.",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest-api/application/upload-vo-d-file",
          label: "Upload external VoD file to Ant Media Server",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
